
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Wed Jan 26 03:03:29 CET 2022
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LTE = 39;
  public static final int CHAR = 51;
  public static final int CONST = 18;
  public static final int LPAREN = 9;
  public static final int SEMI = 5;
  public static final int CONTINUE = 23;
  public static final int MINUS = 41;
  public static final int RPAREN = 10;
  public static final int AND = 16;
  public static final int LT = 40;
  public static final int RECORD = 14;
  public static final int OR = 17;
  public static final int BOOL = 50;
  public static final int COMMA = 6;
  public static final int CLASS = 12;
  public static final int INC = 27;
  public static final int DIV = 44;
  public static final int PLUS = 42;
  public static final int IF = 19;
  public static final int THIS = 32;
  public static final int EOF = 0;
  public static final int RETURN = 25;
  public static final int EQUAL = 34;
  public static final int SUPER = 30;
  public static final int NEW = 33;
  public static final int error = 1;
  public static final int MUL = 43;
  public static final int NUMBER = 49;
  public static final int MOD = 45;
  public static final int NEQ = 36;
  public static final int IDENT = 48;
  public static final int BREAK = 22;
  public static final int VOID = 11;
  public static final int GTE = 37;
  public static final int EQU = 35;
  public static final int COLON = 15;
  public static final int LBRACE = 3;
  public static final int ELSE = 20;
  public static final int LSQUARE = 7;
  public static final int READ = 46;
  public static final int ENUM = 31;
  public static final int POINT = 29;
  public static final int GOTO = 24;
  public static final int RSQUARE = 8;
  public static final int WHILE = 21;
  public static final int RBRACE = 4;
  public static final int EXTENDS = 13;
  public static final int PROG = 2;
  public static final int DEC = 28;
  public static final int GT = 38;
  public static final int PRINT = 47;
  public static final int DO = 26;
}

